### PR TITLE
fix #30

### LINKED ISSUE #30: ccall with two parameters called in a dynamo
Here's an example:

```julia
julia> using IRTools: @dynamo, IR

julia> @dynamo function foo(a...)
           ir = IR(a...)
           return ir
       end

julia> mylog2(x) = ccall((:log2, Base.Math.libm), Float64, (Float64,), x)
mylog2 (generic function with 1 method)

julia> foo(mylog2, 3.3)
ERROR: TypeError: in ccall: first argument not a pointer or valid constant expression, expected Ptr, got Tuple{Symbol,String}
Stacktrace:
 [1] mylog2 at ./REPL[3]:1 [inlined]
 [2] foo(::typeof(mylog2), ::Float64) at /home/tshort/.julia/packages/IRTools/pgYVw/src/reflection/dynamo.jl:0
 [3] top-level scope at REPL[4]:1

```

### PR DESCRIPTION
**Pull request by simeonschaub**
This is basically @MikeInnes suggestion in the discussion in #30. Would be great to get this fixed!

### CODE REVIEW

**Comment by MikeInnes** [comment]
Looks good, though I think a link to the issue would be a good idea.

**Comment by simeonschaub** [comment]
Do you mean in the definition of `push!` as a comment?

**Comment by MikeInnes** [comment]
Right, next to the `isexpr foreigncall` bit (since this special case might be confusing for people reading the code without context).

**Comment by simeonschaub** [comment]
Ok, can do!

File: src/ir/ir.jl [hunk 1]
```diff
@@ -625,7 +625,9 @@ new variable. See also [`pushfirst!`](@ref), [`insert!`](@ref).
       %2 = %1 * %1
 """
 function push!(b::Block, x::Statement)
-  x = applyex(a -> push!(b, Statement(x, expr = a)), x)
+  if !isexpr(x.expr, :foreigncall) # needed to avoid #30
```
Comment (MikeInnes) [inline src/ir/ir.jl]:
```suggestion
  if !isexpr(x.expr, :foreigncall) # needed to avoid https://github.com/MikeInnes/IRTools.jl/issues/30
```
I think a link is usually more convenient/obvious (especially on the small chance the repo moves)

**Comment by simeonschaub** [comment]
Friendly bump☺️

**Comment by MikeInnes** [comment]
:+1: Thanks!
